#159951817 Users should be able Signup/Register to Authors Haven
andela/ah-frontend-taces pull request #14
Opened 2018-09-07 11:10 UTC by AGMETEOR

#### What does this PR do?
To be able to use the application and access authenticated routes, Users should be able to Signup and or Register using Sign up forms on the signup route. Therefore, this PR adds a Signup form where users can register onto Authors Haven.

#### What are the relevant pivotal tracker stories?
[#159951817](https://www.pivotaltracker.com/story/show/159951817)

#### Screenshots
<img width="1440" alt="screen shot 2018-09-07 at 14 09 33" src="https://user-images.githubusercontent.com/28563179/45215956-b3c33f00-b2a7-11e8-9170-301bc7cd3462.png">

2018-09-07 11:15 UTC, phillipseryazi approved these changes

2018-09-07 11:21 UTC, geofrocker reviewed
Resolve merge conflicts

2018-09-07 11:21 UTC, geofrocker commented on src/components/Spinner/Spinner.css
> +}
EOF missing

2018-09-07 11:36 UTC, ssewilliam requested changes
@AGMETEOR ,
This PR is failing on Heroku,
https://authors-haven-front-pr-14.herokuapp.com/

2018-09-07 14:25 UTC, ssewilliam commented
@AGMETEOR 
- the APP crashes when I try to register

<img width="1059" alt="screen shot 2018-09-07 at 17 23 18" src="https://user-images.githubusercontent.com/21138053/45224582-fba38f80-b2c2-11e8-9b7b-02385649cf2e.png">

2018-09-07 14:26 UTC, ssewilliam submitted a review, later dismissed

2018-09-07 14:42 UTC, ssewilliam submitted a review, later dismissed

2018-09-07 14:43 UTC, AGMETEOR commented
@ssewilliam I have rectified the issue. The URLs were still using localhost and not Heroku.

2018-09-07 15:40 UTC, AGMETEOR commented
@ssewilliam I had missed the callback URL in the request data and so redux was dispatching a fail action. The state was therefore not being changed and consequently render the right message. I have fixed it now.

2018-09-07 16:41 UTC, ssewilliam approved these changes

2018-09-10 09:57 UTC, abulojoshua1 requested changes

2018-09-10 09:57 UTC, abulojoshua1 commented on src/store/actions/registerActions.js
> +import * as actionTypes from './actionTypes';
Please remove these wildcards @AGMETEOR.

2018-09-10 10:33 UTC, AGMETEOR commented on src/store/actions/registerActions.js
> +import * as actionTypes from './actionTypes';
@abulojoshua1 let me take them out.

2018-09-10 11:20 UTC, geofrocker commented
Use an alert for this message and clear the fields after successful registration
<img width="456" alt="screen shot 2018-09-10 at 2 18 19 pm" src="https://user-images.githubusercontent.com/22788274/45294595-8d4e0f80-b504-11e8-907e-b90972b64609.png">

2018-09-10 14:46 UTC, abulojoshua1 approved these changes

2018-09-10 18:49 UTC, AGMETEOR commented
@geofrocker I have finished the changes.

2018-09-11 06:50 UTC, geofrocker commented
Cool

2018-09-11 06:50 UTC, merged