#159951811 setup redux on Authors Haven front end
andela/ah-frontend-taces pull request #3
Opened 2018-08-27 16:17 UTC by abulojoshua1

### What does this PR do?
- Setup redux on Authors Haven frontend

### Description of Task to be completed?
- The **PR** sets up redux on the empty react project that was created.

### How should this be manually tested?
- Comment out unnecesary code on and ....

### Any background context you want to provide?
- I installed redux
- Installed react-redux
- created  a store directory that holds reducers and actions
- created an index file in store/actions that combines all reducers

### What are the relevant pivotal tracker stories?
- [#159951811](https://www.pivotaltracker.com/story/show/159951811)

2018-08-27 17:11 UTC, AGMETEOR reviewed
Does this set up use REDUX DEV TOOLS?  Something like this 
 const store = createStore(
   reducer, /* preloadedState, */
+  window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__()
 );

2018-08-28 07:00 UTC, abulojoshua1 commented
@AGMETEOR, thanks for identifying this. It will be quite helpful to us in this project. I will implement it ASAP and get back to you.

2018-08-28 08:00 UTC, phillipseryazi approved these changes

2018-08-28 08:06 UTC, lytes20 approved these changes

2018-08-28 09:10 UTC, geofrocker commented
@abulojoshua1 Remove the commented code. Just add comments on how the files should be used

2018-08-28 09:12 UTC, geofrocker requested changes

2018-08-28 09:12 UTC, geofrocker commented on src/store/reducers/auth_reducer.js
> +/*
Remove this file

2018-08-28 09:19 UTC, abulojoshua1 commented on src/store/reducers/auth_reducer.js
> +/*
ok, I will do just that

2018-08-28 09:47 UTC, ssewilliam approved these changes

2018-08-28 11:17 UTC, merged