#159951829 Users should be able to follow each other
andela/ah-frontend-taces pull request #30
Opened 2018-09-17 06:51 UTC by Seryazi-Andela

#### What does this PR do?
Allows a user to follow or unfollow an Author 
#### Description of Task to be completed?
I want to be able to follow and or unfollow other authors.
#### How should this be manually tested?
Log into authors haven view an article and find the 'follow authors' button at the bottom of the article
#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/159951829
#### Screenshots (if appropriate)

2018-09-17 09:50 UTC, AGMETEOR commented
@Seryazi-Andela Please update the followers and following to reflect the actual number. For example, in the screenshot I see you are following only @abulojoshua1, then the following stats should be 1 :)

2018-09-17 11:52 UTC, Seryazi-Andela commented
its done

2018-09-18 14:49 UTC, geofrocker commented on src/CSS/editProfileModal.css
> +}
missing EOF

2018-09-18 14:53 UTC, geofrocker requested changes

2018-09-18 14:53 UTC, geofrocker commented on src/tests/containers/FollowGrid.test.js
> +      console.log('>>>>>', wrapper.instance().fetchData());
Remove console.log statements

2018-09-18 14:53 UTC, geofrocker commented on src/tests/containers/FollowerGrid.test.js
> +      console.log('>>>>>', wrapper.instance().fetchData());
same here

2018-09-18 14:53 UTC, Seryazi-Andela commented on src/tests/containers/FollowerGrid.test.js
> +      console.log('>>>>>', wrapper.instance().fetchData());
let me work on all

2018-09-18 15:15 UTC, lytes20 commented
When I try to read an article on this PR's app, could please find out what is causing this! @Seryazi-Andela 
<img width="1105" alt="screen shot 2018-09-18 at 18 13 17" src="https://user-images.githubusercontent.com/25790450/45697577-c45c9a80-bb6e-11e8-9249-7ae513dbd28a.png">

2018-09-18 15:19 UTC, ssewilliam commented
@lytes20,
- This is a bug that is not for this PR.this is coming in because the article was deleted

2018-09-18 15:20 UTC, lytes20 commented
@ssewilliam thank you for the clarification

2018-09-18 15:21 UTC, lytes20 approved these changes

2018-09-18 15:25 UTC, ssewilliam reviewed
@Seryazi-Andela 
- There are two more commented lines that you have not taken out.

2018-09-18 15:25 UTC, ssewilliam commented on src/components/Profile/PersonCard.js
> +    // console.log('unfollow clicked');
@Seryazi-Andela 
- this is another commented line

2018-09-18 15:25 UTC, ssewilliam commented on src/components/Profile/FollowerCard.js
> +    // console.log('unfollow clicked');
@Seryazi-Andela 
- This is commented code.

2018-09-18 15:52 UTC, ssewilliam approved these changes

2018-09-19 11:36 UTC, merged