#160094811 Setup ESLint
andela/ah-frontend-taces pull request #8
Opened 2018-08-29 15:10 UTC by lytes20

#### What does this PR do?
- Setup Eslint
#### Description of Task to be completed?
- Configure Eslint for identifying and reporting on patterns in JavaScript
#### How should this be manually tested?
- By writting react javascript code that does not follow `AirBnb` style guidelines
#### Any background context you want to provide?
- Setup `ESLint`, set up `Prettier`. Prettier formats the code based on ESLint rules. And the ESLint rules are those of AirBnb
#### What are the relevant pivotal tracker stories?
[#160094811](https://www.pivotaltracker.com/story/show/160094811)
#### Screenshots (if appropriate)
Lint errors show on trying to run the app
<img width="1047" alt="screen shot 2018-08-29 at 18 07 51" src="https://user-images.githubusercontent.com/25790450/44796857-919a3480-abb6-11e8-8e7f-6e00d9e9c37c.png">

2018-08-29 16:20 UTC, RutaleIvanPaul reviewed
Any effect of setting up  ESlint to the Prettier extension?  https://www.youtube.com/watch?v=YIvjKId9m2c seems to suggest there could be conflicts

2018-08-29 16:44 UTC, lytes20 commented
Hey, @RutaleIvanPaul the video u sent explains how you can resolve an issue of having both Prettier and ESLint extensions set up and enabled in your VScode, If both of them are enabled for your VScode, they will both try to format your code. So you only need one installed.
Prettier is, however, recommended to format the code. So u can just use ESLint to enforce the guidelines. Prettier is only a code "formatter" and can not highlight when you don't follow guidelines.
Also, prettier is code rules suggest double quotes by default but i override this rule as seen in this screenshot below.
<img width="1168" alt="screen shot 2018-08-29 at 19 41 48" src="https://user-images.githubusercontent.com/25790450/44802132-974a4700-abc3-11e8-98c9-97fc7aebb94a.png">
There are basically no conflicts in this setup as regards Prettier and ESLint.
You just need to make sure you also avoid them locally in your VScode configurations

2018-08-29 16:58 UTC, AGMETEOR approved these changes

2018-08-30 13:54 UTC, abulojoshua1 approved these changes

2018-08-30 13:57 UTC, phillipseryazi approved these changes

2018-08-30 14:01 UTC, RutaleIvanPaul approved these changes

2018-08-31 07:27 UTC, ssewilliam approved these changes

2018-08-31 08:20 UTC, geofrocker requested changes

2018-08-31 08:20 UTC, geofrocker commented on .eslintrc.json
> +  "plugins": ["prettier"],
Any reason why you are not using the react plugin

2018-08-31 09:12 UTC, lytes20 commented
@geofrocker, i have included the react plugin

2018-08-31 11:34 UTC, merged